### ISSUE TITLE
i18n repo organization - putting ENGLISH in another repo

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/i18n#97]
Hello Jack.

After a thorough discussion with Andreas (who maintains the Deutsch locale), we think it would be much easier to have two i18n repos:
- one with English language only
- one with all other languages

a) On the i18n English repo, we need "you" (Statamic) to update the English files each and every time you update Statamic
b) we also need version tags (ie 2.9.2, 2.9.3..) on the commits
c) and we really need a way for translators to identify what were the changes made: you can easily do so with a version comparison that should appear on a Readme file in this repo.
Take a look at that:  https://github.com/EllisLab/EE-Language-English/compare/4.1.3...4.2.0 (you can also compare between commits)

Then, on the other repo, we could proceed as we do today with Pull Requests from the various translators and a single Readme file to follow on the latest version that has been translated.

Would you mind telling us what you think of that?

**Comment by jackmcdade** [comment]
Yeah that's a good idea. We'll work out the best way to automate or simplify it too. Thanks!

**Comment by jsbls** [comment]
Was about to open a new issue for this, but huge +1. I just updated the Spanish translations after missing a couple of releases and I'm still not sure I got everything.

Maybe try:
- [https://poedit.net/](https://poedit.net/)
- [https://pootle.translatehouse.org/](https://pootle.translatehouse.org/)

**Comment by ebeauchamps** [comment]
I really think we need that new repo organisation. I understand the Gentlemen are busy working on V3, but the current way CP translations are handled is kind of a "barrier" for getting updated translations or newer ones.

**Comment by AndreasSchantl** [comment]
I totally agree. But why not make the launch of V3 a good starting point for that change. 

I highly doubt for my part that this change will happen with the v2-translations. But more likely this will happen with V3.

**Comment by ebeauchamps** [comment]
Closing this as it does not appear to be the way chosen by the Gentlemen for v3
